name: REACT-COMPONENTS

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main,master]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:16
    strategy:
      matrix:
        package: [frontend]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: run test components
        run: pnpm run test